import Footer from '@/components/commons/footer';
import Header from '@/components/commons/header';
import Navbar from '@/components/commons/navbar';
import { inter } from './fonts';
import './globals.css';

export const metadata = {
  title: 'Home | David',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header></Header>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
